### ISSUE TITLE
Object.copy does not use `UploadPartCopy` for an s3<->s3 transfer

### ISSUE THREAD

**Issue by vincer** [terricain/aioboto3#335]
* Async AWS SDK for Python version: 12.4.0
* Python version: 3.12.3
* Operating System: macOS 14.4.1

### Description

I'm doing an S3 to S3 copy of a large file (multiple GB) which should happen S3-side only using [UploadPartCopy](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html). Instead, it seems to be downloading and then reuploading the object using [UploadPart](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html). The end result is the same, but the download/upload is unnecessary, wasting bandwidth and takes longer.

Works as expected with `boto3`. https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/object/copy.html

### What I Did

```
        b = await s3.Bucket("destination")
        obj = await b.Object("key")
        await obj.copy({"Bucket": "source", "Key": "key"})
```

in boto3 it works as expected:
```
        b = s3.Bucket("destination")
        obj = b.Object("key")
        obj.copy({"Bucket": "source", "Key": "key"})
```

**Comment by terricain** [comment]
Yeah thats expected as when the code was written, UploadPartCopy did not exist :D

**Comment by terricain** [comment]
In v13.0.0 the `s3.copy` function has been rewritten and now utilises `s3.copy_object` or `s3.upload_part_copy`. FYI the default threshold in the S3 Transfer config object is 8MiB, `s3.copy` can copy objects up to 5GiB so bumping that for copies probably makes sense.

**Comment by vincer** [comment]
> UploadPartCopy did not exist

That would do it! Thanks for the quick turnaround!
