### ISSUE TITLE
Request to update aiobotocore version for additional Bedrock support.

### ISSUE THREAD

**Issue by swhite-oreilly** [terricain/aioboto3#350]
* Async AWS SDK for Python version: 2.13.1
* Python version: 3.11.10
* Operating System: Linux

### Description

Utilizing the current version of aioboto3 (13.1.1) pins aiobotocore[boto3]==2.13.1.  Unfortunatly this version of aiobotocore doesn't include support for [batch_delete_evaluation_job](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/bedrock/client/batch_delete_evaluation_job.html).  I haven't determined when this was added to the boto client, but it appears to be present with aiobotocore versions greater than 2.15.x.   When can we expect to see this dependency get updated?

### What I Did

1, Created an evaluation job via the cli (note this fails, but doesn't matter for testing purposes):
```
        echo "Creating IAM role for model evaluation job"
        aws iam create-role \
        --role-name bedrock-eval-role-$SHORT_RANDOM_STRING \
        --assume-role-policy-document '{
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "bedrock.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }' \
        
        echo "Attaching policies to the IAM role"
        aws iam attach-role-policy \
        --role-name bedrock-eval-role-$SHORT_RANDOM_STRING \
        --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess \
        
        aws iam attach-role-policy \
        --role-name bedrock-eval-role-$SHORT_RANDOM_STRING \
        --policy-arn arn:aws:iam::aws:policy/AmazonBedrockFullAccess \
        
        # Wait for a few seconds to ensure the role is fully propagated
        echo "Waiting for IAM role propagation..."
        sleep 10
        
        # Create a unique S3 bucket name
        S3_BUCKET_NAME="automatic-eval-jobs-$SHORT_RANDOM_STRING"
        
        echo "Creating S3 bucket for output data"
        aws s3 mb s3://$S3_BUCKET_NAME
        
        echo "Creating model evaluation job"
        aws bedrock create-evaluation-job \
        --job-name "automatic-eval-job-cli-$SHORT_RANDOM_STRING" \
        --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID:role/bedrock-eval-role-$SHORT_RANDOM_STRING" \
        --evaluation-config '{"automated": {"datasetMetricConfigs": [{"taskType": "QuestionAndAnswer","dataset": {"name": "Builtin.BoolQ"},"metricNames": ["Builtin.Accuracy","Builtin.Robustness"]}]}}' \
        --inference-config '{"models": [{"bedrockModel": {"modelIdentifier":"arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-text-lite-v1","inferenceParams":"{\"temperature\":\"0.0\", \"topP\":\"1\", \"maxTokenCount\":\"512\"}"}}]}' \
        --output-data-config '{"s3Uri":"s3://'$S3_BUCKET_NAME'/outputs"}' 
```
2. Attempt cleanup of the evaluation job.
```
    from typing import cast
    from types_aiobotocore_bedrock.client import BedrockClient
    import aioboto3
    
    async def main():
       session = aioboto3.Session()
       async with session.client("bedrock") as bedrock_client:
                evaluation_paginator = bedrock_client.get_paginator("list_evaluation_jobs")
            
                job_identifiers = []
            
                async for page in evaluation_paginator.paginate():
                    for job in page["jobSummaries"]:
                        job_identifiers.append(job["jobArn"])
            
                if job_identifiers:
                    await bedrock_client.batch_delete_evaluation_job(jobIdentifiers=job_identifiers)
```

This fails with the currently implemented version of aiobotocore stating this function wasn't found, but if you manually upgrade this to the latest, currently `2.15.1` it will succeed.

**Comment by terricain** [comment]
`13.2.0` is out which uses aiobotocore 2.15.2, give that a go.

**Comment by dhungana** [comment]
Now aiobotocore is pinned at 2.15.2. However, it has been upgraded to 2.16.0 which uses later versions of boto3 and botocore that I need for additional functionalities.

Is it possible to pin it to 2.16.0 or not pin it on a single version?
https://github.com/terricain/aioboto3/blob/main/pyproject.toml#L27

**Comment by terricain** [comment]
So whilst I'd like to not pin aiobotocore to a specific version, this library patches specific boto3 methods, so therefore relaxing the requirement on aiobotocore relaxes the requirement on boto3 which then opens up the can of worms that is this library not patching boto3 correctly, which then is a nightmare to diagnose.

`13.3.0` is out.
